# Generated by Django 2.2.7 on 2019-12-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('finger', models.CharField(blank=True, db_column='Finger', max_length=50, null=True)),
                ('identify', models.CharField(blank=True, db_column='Identify', max_length=50, null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
    ]
